baseURL = 'https://economikit.org/'
title = 'Economikit Alliance'
theme = 'ek'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
# googleAnalytics = "UA-XXXXXXXXX-X"

# (:TODO:) If you provide a Disqus shortname, comments will be enabled on
# all pages.
# disqusShortname = "my-site"

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ["taxonomyTerm", "taxonomy"]

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1
